import type { Metadata } from "next";
import "./reset.css";
import "./globals.css";
import { Cinzel_Decorative, Dancing_Script, Roboto } from "next/font/google";
import { Header } from "@/components/header/header";
import { Analytics } from "@vercel/analytics/next";

const cinzelDecorative = Cinzel_Decorative({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-cinzel-decorative",
});

const dancingScript = Dancing_Script({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-dancing-script",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: React.PropsWithChildren<{}>) {
  return (
    <html
      lang="en"
      className={`${cinzelDecorative.variable} ${dancingScript.variable} ${roboto.variable}`}
    >
      <body>
        <Header />
        <main>
          <div className="page">{children}</div>
        </main>
        <Analytics />
      </body>
    </html>
  );
}
