import type { Metadata } from "next";
import "./reset.css";
import "./globals.css";
import { Cinzel_Decorative } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import { NextIntlClientProvider } from "next-intl";
import { Link } from "@/i18n/navigation";
import { getTranslations } from "next-intl/server";
import { LocaleSwitcher } from "@/components/LocaleSwitcher/LocaleSwitcher";

const cinzelDecorative = Cinzel_Decorative({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-cinzel-decorative",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}

export default async function RootLayout({ params, children }: Props) {
  const t = await getTranslations();
  const { locale } = await params;

  return (
    <html
      lang={locale}
      className={`${cinzelDecorative.variable}`}
    >
      <body>
        <NextIntlClientProvider>
          <header>
            <Link href="/" className="site-title">
              {t("common.anthony-and-lloyd")}
            </Link>
            <LocaleSwitcher />
          </header>
          <main>
            <div>{children}</div>
          </main>
          <Analytics />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
